name: Android CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  JAVA_VERSION: 17
  BUILD_TYPE: Debug
  APK_PATH: app/build/outputs/apk/debug/app-debug.apk

jobs:

  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      gradle-cache-key: ${{ steps.cache.outputs.cache-primary-key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: ./gradlew lint${{ env.BUILD_TYPE }}

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: ./gradlew test${{ env.BUILD_TYPE }}UnitTest

  build:
    name: Build APK
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Build Debug APK
        run: ./gradlew assemble${{ env.BUILD_TYPE }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ env.BUILD_TYPE }}.apk
          path: ${{ env.APK_PATH }}
