name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build & Test Android
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: 17
      ANDROID_API_LEVEL: 34
      ANDROID_BUILD_TOOLS_VERSION: 34.0.0

    steps:
      ##########################################
      # SETUP
      ##########################################
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      ##########################################
      # LINT
      ##########################################
      - name: Run lint
        run: ./gradlew lintDebug

      ##########################################
      # TEST
      ##########################################

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      ##########################################
      # BUILD
      ##########################################
      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk